FROM ubuntu/apache2
WORKDIR /var/www/html/
RUN apt-get update -y 
RUN apt-get install -y php \
    libapache2-mod-php \
    php-mysql \
    php-mbstring \
    php-zip \
    php-gd \
    php-json \
    php-curl

